function getConstants() {
    return {
        errors: {
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Failed',
            '413': 'Payload Too Large',
            '414': 'URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': "I'm a teapot",
        },
        hands: [
            ['Lose', 0],
            ['Jacks or Better', 1],
            ['Two Pair', 2],
            ['Three of a Kind', 3],
            ['Straight', 4],
            ['Flush', 6],
            ['Full House', 9],
            ['Four of a Kind', 25],
            ['Straight Flush', 50],
            ['Royal Flush', 800],
        ],
        ranks: [
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            't',
            'j',
            'q',
            'k',
            'a',
        ],
        suits: ['s', 'h', 'c', 'd'],
        colors: {
            's': '#1F191B',
            'c': '#1F191B',
            'h': '#CB1728',
            'd': '#CB1728',
        },
        stringMap: {
            'as': '\ud83c\udca1',
            'ah': '\ud83c\udcb1',
            'ad': '\ud83c\udcc1',
            'ac': '\ud83c\udcd1',
            '2s': '\ud83c\udca2',
            '2h': '\ud83c\udcb2',
            '2d': '\ud83c\udcc2',
            '2c': '\ud83c\udcd2',
            '3s': '\ud83c\udca3',
            '3h': '\ud83c\udcb3',
            '3d': '\ud83c\udcc3',
            '3c': '\ud83c\udcd3',
            '4s': '\ud83c\udca4',
            '4h': '\ud83c\udcb4',
            '4d': '\ud83c\udcc4',
            '4c': '\ud83c\udcd4',
            '5s': '\ud83c\udca5',
            '5h': '\ud83c\udcb5',
            '5d': '\ud83c\udcc5',
            '5c': '\ud83c\udcd5',
            '6s': '\ud83c\udca6',
            '6h': '\ud83c\udcb6',
            '6d': '\ud83c\udcc6',
            '6c': '\ud83c\udcd6',
            '7s': '\ud83c\udca7',
            '7h': '\ud83c\udcb7',
            '7d': '\ud83c\udcc7',
            '7c': '\ud83c\udcd7',
            '8s': '\ud83c\udca8',
            '8h': '\ud83c\udcb8',
            '8d': '\ud83c\udcc8',
            '8c': '\ud83c\udcd8',
            '9s': '\ud83c\udca9',
            '9h': '\ud83c\udcb9',
            '9d': '\ud83c\udcc9',
            '9c': '\ud83c\udcd9',
            'ts': '\ud83c\udcaa',
            'th': '\ud83c\udcba',
            'td': '\ud83c\udcca',
            'tc': '\ud83c\udcda',
            'js': '\ud83c\udcab',
            'jh': '\ud83c\udcbb',
            'jd': '\ud83c\udccb',
            'jc': '\ud83c\udcdb',
            'qs': '\ud83c\udcad',
            'qh': '\ud83c\udcbd',
            'qd': '\ud83c\udccd',
            'qc': '\ud83c\udcdd',
            'ks': '\ud83c\udcae',
            'kh': '\ud83c\udcbe',
            'kd': '\ud83c\udcce',
            'kc': '\ud83c\udcde',
        },
    };
}
