function getConstants() {
    return {
        errors: {
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Failed',
            '413': 'Payload Too Large',
            '414': 'URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': "I'm a teapot",
        },
        hands: [
            ['Lose', 0],
            ['Jacks or Better', 1],
            ['Two Pair', 2],
            ['Three of a Kind', 3],
            ['Straight', 4],
            ['Flush', 6],
            ['Full House', 9],
            ['Four of a Kind', 25],
            ['Straight Flush', 50],
            ['Royal Flush', 800],
        ],
        ranks: [
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            't',
            'j',
            'q',
            'k',
            'a',
        ],
        suits: ['s', 'h', 'c', 'd'],
        colors: {
            's': '#1F191B',
            'c': '#1F191B',
            'h': '#CB1728',
            'd': '#CB1728',
        },
        stringMap: {
            'as': '🂡',
            'ah': '🂱',
            'ad': '🃁',
            'ac': '🃑',
            '2s': '🂢',
            '2h': '🂲',
            '2d': '🃂',
            '2c': '🃒',
            '3s': '🂣',
            '3h': '🂳',
            '3d': '🃃',
            '3c': '🃓',
            '4s': '🂤',
            '4h': '🂴',
            '4d': '🃄',
            '4c': '🃔',
            '5s': '🂥',
            '5h': '🂵',
            '5d': '🃅',
            '5c': '🃕',
            '6s': '🂦',
            '6h': '🂶',
            '6d': '🃆',
            '6c': '🃖',
            '7s': '🂧',
            '7h': '🂷',
            '7d': '🃇',
            '7c': '🃗',
            '8s': '🂨',
            '8h': '🂸',
            '8d': '🃈',
            '8c': '🃘',
            '9s': '🂩',
            '9h': '🂹',
            '9d': '🃉',
            '9c': '🃙',
            'ts': '🂪',
            'th': '🂺',
            'td': '🃊',
            'tc': '🃚',
            'js': '🂫',
            'jh': '🂻',
            'jd': '🃋',
            'jc': '🃛',
            'qs': '🂭',
            'qh': '🂽',
            'qd': '🃍',
            'qc': '🃝',
            'ks': '🂮',
            'kh': '🂾',
            'kd': '🃎',
            'kc': '🃞',
        },
    };
}
